# Generated by Django 2.1.5 on 2019-10-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vil_app', '0002_auto_20191003_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
