# Generated by Django 2.1.5 on 2019-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vil_app', '0004_auto_20191008_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='published_date',
        ),
        migrations.AddField(
            model_name='page',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
